:PROPERTIES:
:ID:       6b88a1c9-21e7-43d3-b0db-d312b2e1bf6f
:END:
#+title: Figure out what you'll do wrong and don't do that
#+created: [2021-09-26 Sun 10:28]
#+last_modified: [2021-09-26 Sun 10:49]
At the first stages of learning something new, it's mostly about not doing things wrong. Figure out what those things are. Ask an instructor what people usually do wrong. Between attempts, look at your last attempt and see what went wrong. Then, don't do that. This is easier than it sounds.

Some things people get wrong are because they didn't know. It's not that wrong is easier than right. They just needed to look or ask.

You can usually trade one wrong thing for another. You came in too low last time. This time your height was good, but your speed was off. This process is fine. Better to have new problems.

My favorite time I did this was the first time I made ravioli. I looked at them. They didn't look good. They were too fat. The edges were too wide. The pasta was too thick. Okay. Less filling, flatten it out, roll the dough thinner. The second set I would have been happy to get at a restaurant.
